name: Build and deploy to gh pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    # No tests of value yet, so don't bother spinning them up
    # - run: npm test

    # Now let's throw it at gh-pages. 
    - name: Deploy
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email chris@cpprograms.net
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages -d build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
