name: Build and deploy to gh pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    # No tests of value yet, so don't bother spinning them up
    # - run: npm test

    # Now let's throw it at gh-pages. 
    - name: Deploy
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email automation@nes.science
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        export NPM_PACKAGE_VERSION=$(node -e "console.info(require('./package.json').version)")
        export REACT_APP_VERSION=$NPM_PACKAGE_VERSION
        echo "Going to deploy version $NPM_PACKAGE_VERSION $REACT_APP_VERSION"
        npm run build-gh
        npx gh-pages -d build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
