name: Build and deploy to gh pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    # No tests of value yet, so don't bother spinning them up
    # - run: npm test

    # Now let's have some fun. Whomp the main repo and push to gh-pages branch
    - run: git branch -d gh-pages || echo "Branch not there, continue"
    - run: git checkout -b gh-pages
    - name: Deploy
      run: |
        git config --global user.name Github Actions
        git config --global user.email chris@cpprograms.net
        git remote set-url origin https://${github_token@github.com/${repository}
        gh-pages -d build
      env:
        repository: ${{ github.repository }}
        github_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}